services:
  db:
    image: postgres:16
    container_name: django_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s      # 5초마다 검사
      timeout: 1s
      retries: 5
  
  web:
    # Django 백엔드
    build:
      context: ./backend  # Django Dockerfile 위치
      dockerfile: Dockerfile
    container_name: django_web
    volumes:
      - ./backend:/app  # 로컬의 backend 폴더를 컨테이너 /app에 마운트
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    # Svelte 프론트엔드
    build:
      context: ./frontend # Svelte Dockerfile 위치
      dockerfile: Dockerfile
    container_name: svelte_frontend
    volumes:
      - ./frontend:/app
    # Svelte Vite 개발 서버 포트를 매핑 (보통 5173, 필요에 따라 바꿔도 됨)
    ports:
      - "5173:5173"
    depends_on:
      - web
    environment:
      # 혹시 프론트에서 백엔드 API 호출 시 필요한 설정이 있다면
      - VITE_API_URL=http://localhost:8000